Add English texts to CONTRIBUTING.md. Modify Japanese texts.
rt-net/.github pull request #14
Opened 2023-12-08 08:34 UTC by ShotaAk

# What does this implement/fix?

CONTRIBUTING.mdに英文を追加します。
また、英文を作りやすくるため、日本語文も修正します。

# Does this close any currently open issues?

いいえ

# Checklists

- [x]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2023-12-08 10:34 UTC, Tiryoh requested changes
2点変更リクエストです。 （@shu-rt のコメントを優先してください）

2023-12-08 10:34 UTC, Tiryoh commented on CONTRIBUTING.md
> +  - Not all PRs will be merged, and some may not meet your expectations.
```suggestion
  - Not all PRs will be merged and the review process may take some time.
```

2023-12-08 10:34 UTC, Tiryoh commented on CONTRIBUTING.md
> +- If you have a test set up in the repository, please test it as much as possible.
```suggestion
- For requests to repositories where CI and tests are set up, please try to pass the tests as much as possible.
```

2023-12-11 06:26 UTC, shu-13 reviewed
細かい部分ですが、確認お願いします。  
また、大亮のコメントに関しては同意です。

2023-12-11 06:26 UTC, shu-rt commented on CONTRIBUTING.md
> +  - If you submit a PR without testing for some reason (e.g., if there is a mistake in the testing), please indicate this in the PR.
```suggestion
  - If you submit a PR without testing for a specific reason (e.g., if there is a mistake in the testing), please describe it in the PR.
```

2023-12-11 06:26 UTC, shu-rt commented on CONTRIBUTING.md
> +- Keep changes requested in a single PR as simple as possible
```suggestion
- Keep the changes requested in a single PR as simple as possible
```

2023-12-11 06:26 UTC, shu-rt commented on CONTRIBUTING.md
>  # Contribution Guide
```suggestion
# Contribution Guide (EN)
```

2023-12-11 06:26 UTC, shu-rt commented on CONTRIBUTING.md
> +# Contribution Guide
```suggestion
# Contribution Guide (JA)
```

2023-12-11 12:41 UTC, ShotaAk commented
@Tiryoh @shu-rt 修正取り入れました。ご確認お願いします。

2023-12-11 13:01 UTC, Tiryoh approved these changes

2023-12-12 01:17 UTC, shu-rt approved these changes

2023-12-12 01:19 UTC, merged