Update issue templates
rt-net/.github pull request #6
Opened 2020-04-22 06:09 UTC by ShotaAk

2020-04-22 06:34 UTC, Tiryoh requested changes
今後ほかのテンプレートが追加されることも考えて`-----.md`ではなく`bug_report_ja.md`などにするのがよいと思います。

2020-04-22 06:34 UTC, Tiryoh commented on .github/ISSUE_TEMPLATE/-----.md
> +- ソフトのバージョン: <!-- 例：masterの最新、コミットabcd123 -->
```suggestion
- ソフトのバージョン: <!-- 例：○月○日のmasterの最新、コミットabcd123 -->
```

2020-04-22 06:40 UTC, ShotaAk commented
ファイル名見落としてました、ありがとうございます。
GitHub上で作成すると日本語がハイフンに変換されるようです。

2020-04-22 06:48 UTC, ShotaAk commented
更新しました。

2020-04-22 06:54 UTC, ShotaAk commented
デフォルトラベルが更新されていたので反映します

2020-04-23 08:34 UTC, Tiryoh reviewed
lgtm

2020-04-23 08:34 UTC, Tiryoh approved these changes

2020-04-23 08:34 UTC, merged