Add CONTRIBUTING.md
rt-net/.github pull request #8
Opened 2020-04-22 08:46 UTC by ShotaAk

2020-04-22 10:11 UTC, Tiryoh requested changes
明日再度確認します。今日の時点で気になったところにコメント付けました。

2020-04-22 10:11 UTC, Tiryoh commented on CONTRIBUTING.md
> +- PRは`rt-net`のメンバーにレビューされます
```suggestion
- PRは`rt-net`のメンバーにレビューを経てからマージされます
    - すべてのPRがマージされるわけではなく、希望に添えない場合もありますのでご容赦ください
```

2020-04-22 10:11 UTC, Tiryoh commented on CONTRIBUTING.md
> +  - テストの間違いがある場合はその旨をPRに記載してください
```suggestion
  - 何かしらの理由（テストに間違いがある場合など）でテストを通さずPRを出す場合はその旨をPRに記載してください
```

機能追加の際にテストがない（間違っているわけではない）場合についてもフォローした表記だといいと思います。

2020-04-22 10:11 UTC, Tiryoh commented on CONTRIBUTING.md
> +- PRのコミットは`squash`されます
```suggestion
- マージする際にはPR内の全コミットが1つのコミットに`squash`されます
```

2020-04-22 10:11 UTC, Tiryoh commented on CONTRIBUTING.md
> +  - `squash`しても履歴を辿りやすくなります
```suggestion
- 1つのPRでリクエストする変更はできるだけシンプルにしてください
  - 異なる内容の変更を含むの場合はPRは分割してください
      - 例えば、複数の機能追加、機能追加とリファクタリングを同時にしたいなど場合はそれぞれ別々のPRとしてください
  - squashマージしても履歴を辿りやすくするためです
```

2020-04-22 10:11 UTC, Tiryoh commented on CONTRIBUTING.md
> +- PRの内容には本リポジトリの[LICENSE](./LICENSE)が適用されます
```suggestion
- PRの内容には本リポジトリのライセンス（[LICENSE](./LICENSE)と[README.md](./README.md)に記載されています）が適用されます
```

ライセンスによっては著作権表記がLICENSEファイルに含まれない場合もあるので、それについて考慮しました。

2020-04-23 04:36 UTC, ShotaAk commented
修正案ありがとうございます。
一部整えて取り入れました。

2020-04-23 08:38 UTC, Tiryoh requested changes

2020-04-23 08:38 UTC, Tiryoh commented on CONTRIBUTING.md
> +- PRは`rt-net`のメンバーにレビューを経てからマージされます
```suggestion
- PRは`rt-net`のメンバーのレビューを経てからマージされます
```

昨日の提案の際にtypoしてました。

2020-04-23 09:40 UTC, ShotaAk commented on CONTRIBUTING.md
> +- PRは`rt-net`のメンバーにレビューを経てからマージされます
これは日本語難しい案件。

`の`が２連続になるので、`rt-netのメンバーによるレビュー`に書き換えようかと思います。

2020-04-24 00:58 UTC, ShotaAk commented
修正案を取り入れました

2020-04-24 07:12 UTC, Tiryoh approved these changes
lgtm

2020-04-24 07:12 UTC, merged