Add pull request template
rt-net/.github pull request #9
Opened 2020-04-24 03:09 UTC by ShotaAk

# Checklists

- [x]  I have read the [CONTRIBUTING](../CONTRIBUTING.md) document.
- [x]  I have checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same change.

# What does this implement/fix? Explain your changes.

プルリクエストのテンプレートを追加します。

# Does this close any currently open issues?

#3 に関連します。

# How has this been tested?

このPRがテストです。

https://github.com/stevemao/github-issue-templates
を参考にして作成しました。

# Any other comments?

レビューよろしくお願いします。

2020-04-24 09:28 UTC, Tiryoh commented
@ShotaAk 

> I have checked to ensure there aren't other open Pull Requests for the same change.

のリンクをクリックすると自分が作成したプルリクエスト一覧ページに飛ぶのですが、これは意図的ですか？
プロジェクトごとのプルリクエスト一覧に飛ばせるならそちらの方がよい気がします。

2020-04-24 09:29 UTC, Tiryoh reviewed
@ShotaAk 

> I have checked to ensure there aren't other open Pull Requests for the same change.

のリンクをクリックすると自分が作成したプルリクエスト一覧ページに飛ぶのですが、これは意図的ですか？
プロジェクトごとのプルリクエスト一覧に飛ばせるならそちらの方がよい気がします。

2020-05-07 08:48 UTC, ShotaAk commented
> @ShotaAk
> 
> > I have checked to ensure there aren't other open Pull Requests for the same change.
> 
> のリンクをクリックすると自分が作成したプルリクエスト一覧ページに飛ぶのですが、これは意図的ですか？
> プロジェクトごとのプルリクエスト一覧に飛ばせるならそちらの方がよい気がします。

相対パスを間違えてそうなので確認します。

2020-05-07 08:55 UTC, ShotaAk commented
修正しました。

2020-05-13 02:14 UTC, Tiryoh requested changes

2020-05-13 02:14 UTC, Tiryoh commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] <!-- コントリビューティングガイドラインを読みました--> I have read the [CONTRIBUTING](../CONTRIBUTING.md) document.
`PULL_REQUEST_TEMPLATE.md`からは`CONTRIBUTING.md`へのリンクが有効なようですが、Issueページからリンクを踏むと404が出てしまいました。
リンクを消して、とりあえず取り込むのが良いかと思いますがどうでしょう？

2020-05-13 02:15 UTC, Tiryoh commented
一度Assigneeを@ShotaAkさんに戻しますね

2020-05-13 06:28 UTC, ShotaAk commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] <!-- コントリビューティングガイドラインを読みました--> I have read the [CONTRIBUTING](../CONTRIBUTING.md) document.
相対パスがうまくいかないですね。
リンク消します。

2020-05-15 02:31 UTC, Tiryoh approved these changes

2020-05-15 02:31 UTC, merged